version: "3"
services:
  apikeyper-db:
    image: postgres:latest
    container_name: apikeyper-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
    user: postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    # ports:
    #   - "5438:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d # Mount the initdb scripts
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  apikeyper-redis:
    image: redis:latest
    container_name: apikeyper-redis
    restart: always
    # ports:
    #   - "6379:6379"

  apikeyper-api:
    build: .
    container_name: apikeyper-api
    ports:
      - "8080:8080"
    env_file:
      - .env.template
    depends_on:
      apikeyper-db:
        condition: service_healthy

  apikeyper-worker:
    build:
      context: .
      dockerfile: Dockerfile.Worker
    container_name: apikeyper-worker
    env_file:
      - .env.template
    depends_on:
      apikeyper-db:
        condition: service_healthy

volumes:
  dbdata:
