version: "3"
services:
  apikeyper-db:
    image: postgres:latest
    container_name: apikeyper-db
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    user: ${POSTGRES_USER}
    logging:
      options:
        max-size: 10m
        max-file: "3"

    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d # Mount the initdb scripts
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  apikeyper-redis:
    image: redis:latest
    container_name: apikeyper-redis
    restart: always

  apikeyper-api:
    build:
      context: core
      dockerfile: Dockerfile
    container_name: apikeyper-api
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=apikeyper-redis:6379
    depends_on:
      apikeyper-db:
        condition: service_healthy

  apikeyper-worker:
    build:
      context: core
      dockerfile: Dockerfile.Worker
    container_name: apikeyper-worker
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=apikeyper-redis:6379
    depends_on:
      apikeyper-db:
        condition: service_healthy

  apikeyper-dashboard:
    build:
      context: dashboard
      dockerfile: Dockerfile.Web
    container_name: apikeyper-dashboard
    environment:
      - NEXT_PUBLIC_API_URL=http://apikeyper-api:8080
      - DATABASE_URL=${DATABASE_URL}
      - ROOTKEY_PASSWORD=${SECRET_SIGNING_KEY}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
    ports:
      - 3000:3000
    depends_on:
      - apikeyper-api


volumes:
  dbdata:
