name: Go-test
on: [pull_request]

env:
  DATABASE_URL: postgresql://postgres:pass@localhost:5432/apikeyper_test
  REDIS_URL: localhost:6379


jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./core

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: pass
          POSTGRES_DB: apikeyper_test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      redis:
        image: redis:latest
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22.x"

      - name: Build
        run: go build -v ./...
      - name: Test with the Go CLI
        run: go test ./tests/... -p 1
